# PS1="%{%F{033}%}%n%{%f%}@%{%F{green}%}%m:%{%F{yellow}%}%~%{$%f%}%  "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Some Random Settings
ZSH_THEME="cloud"
# ZSH_THEME="robbyrussell"

# Random Plugins
ZSH=~/.oh-my-zsh
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# My Asliases
alias vim="nvim"
alias code="cd ~/Documents/code"
alias dotfiles="cd ~/Documents/code/dotfiles"

# My Path
path+=($HOME/.local/bin $path)

eval "$(starship init zsh)"
